linters-settings:
  depguard:
    rules:
      main:
        allow:
        - $gostd
        - github.com/gin-gonic/gin
        - gitlab.ewi.tudelft.nl/cse2000-software-project/2023-2024/cluster-v/17b/alexandria-backend
  errcheck:
    check-type-assertions: true
  funlen:
    lines: 60
    statements: 50
    ignore-comments: true
  goconst:
    min-len: 2
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  gofmt:
    simplify: true
  govet:
    shadow: true
    # enable:
    #   - fieldalignment
  nolintlint:
    require-explanation: true
    require-specific: true

linters:
  disable-all: true
  enable:
    - asciicheck 
    - bidichk
    - bodyclose
    - decorder
    - depguard
    - dogsled
    - dupl
    - errcheck
    - errorlint
    - exportloopref
    - exhaustive
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gofmt
    - mnd
    - gocyclo
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - nakedret
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - stylecheck
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - wsl

run:
  issues-exit-code: 1
  timeout: 5m
  allow-parallel-runners: true

issues:
  fix: false

output:
  print-issued-lines: true
  print-linter-name: false