linters-settings:
  errcheck:
    check-type-assertions: true
  dupl:
    threshold: 5000
  funlen:
    lines: 80
    statements: 50
    ignore-comments: true
  goconst:
    min-len: 2
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
    - rangeValCopy
  gofmt:
    simplify: true
  govet:
    shadow: true
    # enable:
    #   - fieldalignment
  nolintlint:
    require-explanation: true
    require-specific: true

linters:
  disable-all: true
  enable:
    - asciicheck
    - bidichk
    - decorder
    - dogsled
    - dupl
    - errcheck
    - errorlint
    - exportloopref
    - exhaustive
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gofmt
    - gomnd
    - gocyclo
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - nakedret
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - stylecheck
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - wsl

run:
  issues-exit-code: 1
  timeout: 5m
  allow-parallel-runners: true

issues:
  fix: false
  exclude-rules:
    - path: server/server.go
      text: "Function 'initServiceEnv' is too long"

output:
  print-issued-lines: true
  print-linter-name: true
