services:
  backend:
    container_name: alexandria_backend
    build:
      context: .
      target: run # This should stay as 'run'.
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./:/app
    ports: 
      - 8080:8080
    networks:
      - alexandria_network
    # TODO This is only good for a prototype. Database credentials should not
    # be kept in memory/environment variables in a production context.
    environment: 
      - ALEXANDRIA_DB_HOST=${ALEXANDRIA_DB_HOST}
      - ALEXANDRIA_TEST_DB_HOST=${ALEXANDRIA_TEST_DB_HOST}
      - ALEXANDRIA_TEST_DB_NAME=${ALEXANDRIA_TEST_DB_NAME}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - SECRET=${SECRET}
    depends_on:
      database:
        condition: service_healthy
      test_database:
        condition: service_healthy

  database:
    image: mariadb
    restart: unless-stopped
    environment:
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    # TODO Once we have a separate prod compose.yaml, this port should not be exposed.
    # This port is exposed so that you can inspect the database from your host machine.
    ports:
      - 3306:3306
    networks:
      - alexandria_network
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      interval: 3s
      retries: 100
      test:
        [
          "CMD",
          "healthcheck.sh",
          "--su-mysql",
          "--connect",
          "--innodb_initialized"
        ]
      timeout: 30s

  # TODO this should not be running in production
  test_database:
    image: mariadb
    restart: unless-stopped
    environment:
      - MARIADB_DATABASE=${ALEXANDRIA_TEST_DB_NAME}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    ports:
      - 3307:3306
    networks:
      - alexandria_network
    volumes:
      - test_db_data:/var/lib/mysql
    healthcheck:
      interval: 3s
      retries: 100
      test:
        [
          "CMD",
          "healthcheck.sh",
          "--su-mysql",
          "--connect",
          "--innodb_initialized"
        ]
      timeout: 30s

volumes:
  db_data:
  test_db_data:

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  alexandria_network:
    # name must be specified to ensure it's the same in both frontend an backend
    name: alexandria_network 
