services:
  backend:
    build:
      context: .
      target: builder
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./:/app
    ports:
      - 8080:8080

  database:
    image: mariadb
    restart: unless-stopped
    environment:
      - MARIADB_DATABASE="Alexandria"
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
