services:
  backend:
    build:
      context: .
      target: builder
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./:/app
    ports:
      - 8080:8080
    depends_on:
      database:
        condition: service_healthy

  database:
    image: mariadb
    restart: unless-stopped
    environment:
      - MARIADB_DATABASE="Alexandria"
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      interval: 3s
      retries: 100
      test:
        [
          "CMD",
          "healthcheck.sh",
          "--su-mysql",
          "--connect",
          "--innodb_initialized"
        ]
      timeout: 30s

volumes:
  db_data:
