services:
  builder:
    build:
      context: .
      target: builder
      dockerfile: Dockerfile
      args: 
        - GOPKG=${GOROOT}\pkg
        - GOBIN=${GOROOT}\bin
    stdin_open: true
    tty: true
    volumes:
      - ./:/app
    ports:
      - 8080:8080
