project:
  type: website

website:
  title: "include-relative-paths"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  repo-url: https://github.com/quarto-dev/quarto-examples
  repo-subdir: websites/include-relative-paths

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-tools:
      source: repo

quarto-required-version: ">=1.2.67"


