// Code generated by MockGen. DO NOT EDIT.
// Source: ./postService_interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	forms "gitlab.ewi.tudelft.nl/cse2000-software-project/2023-2024/cluster-v/17b/alexandria-backend/forms"
	models "gitlab.ewi.tudelft.nl/cse2000-software-project/2023-2024/cluster-v/17b/alexandria-backend/models"
)

// MockPostService is a mock of PostService interface.
type MockPostService struct {
	ctrl     *gomock.Controller
	recorder *MockPostServiceMockRecorder
}

// MockPostServiceMockRecorder is the mock recorder for MockPostService.
type MockPostServiceMockRecorder struct {
	mock *MockPostService
}

// NewMockPostService creates a new mock instance.
func NewMockPostService(ctrl *gomock.Controller) *MockPostService {
	mock := &MockPostService{ctrl: ctrl}
	mock.recorder = &MockPostServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostService) EXPECT() *MockPostServiceMockRecorder {
	return m.recorder
}

// CreatePost mocks base method.
func (m *MockPostService) CreatePost(form *forms.PostCreationForm) *models.Post {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePost", form)
	ret0, _ := ret[0].(*models.Post)
	return ret0
}

// CreatePost indicates an expected call of CreatePost.
func (mr *MockPostServiceMockRecorder) CreatePost(form interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePost", reflect.TypeOf((*MockPostService)(nil).CreatePost), form)
}

// CreateProjectPost mocks base method.
func (m *MockPostService) CreateProjectPost(form *forms.ProjectPostCreationForm) *models.ProjectPost {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProjectPost", form)
	ret0, _ := ret[0].(*models.ProjectPost)
	return ret0
}

// CreateProjectPost indicates an expected call of CreateProjectPost.
func (mr *MockPostServiceMockRecorder) CreateProjectPost(form interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProjectPost", reflect.TypeOf((*MockPostService)(nil).CreateProjectPost), form)
}

// GetPost mocks base method.
func (m *MockPostService) GetPost(postID uint64) (*models.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPost", postID)
	ret0, _ := ret[0].(*models.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPost indicates an expected call of GetPost.
func (mr *MockPostServiceMockRecorder) GetPost(postID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPost", reflect.TypeOf((*MockPostService)(nil).GetPost), postID)
}

// GetProjectPost mocks base method.
func (m *MockPostService) GetProjectPost(postID uint64) (*models.ProjectPost, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjectPost", postID)
	ret0, _ := ret[0].(*models.ProjectPost)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjectPost indicates an expected call of GetProjectPost.
func (mr *MockPostServiceMockRecorder) GetProjectPost(postID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectPost", reflect.TypeOf((*MockPostService)(nil).GetProjectPost), postID)
}

// UpdatePost mocks base method.
func (m *MockPostService) UpdatePost(updatedPost *models.Post) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePost", updatedPost)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePost indicates an expected call of UpdatePost.
func (mr *MockPostServiceMockRecorder) UpdatePost(updatedPost interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePost", reflect.TypeOf((*MockPostService)(nil).UpdatePost), updatedPost)
}

// UpdateProjectPost mocks base method.
func (m *MockPostService) UpdateProjectPost(updatedPost *models.ProjectPost) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProjectPost", updatedPost)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProjectPost indicates an expected call of UpdateProjectPost.
func (mr *MockPostServiceMockRecorder) UpdateProjectPost(updatedPost interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProjectPost", reflect.TypeOf((*MockPostService)(nil).UpdateProjectPost), updatedPost)
}
