// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/branches": {
            "put": {
                "description": "Update any number of the aspects of a branch",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "branches"
                ],
                "summary": "Update branch",
                "parameters": [
                    {
                        "description": "Updated Branch",
                        "name": "branch",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.BranchDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            },
            "post": {
                "description": "Create a new branch linked to a project post.\nNote that Member IDs passed here, get converted to Collaborator IDs.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "branches"
                ],
                "summary": "Create new branch",
                "parameters": [
                    {
                        "description": "Branch Creation Form",
                        "name": "form",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/forms.BranchCreationForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.BranchDTO"
                        }
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/branches/collaborators/{collaboratorID}": {
            "get": {
                "description": "Get a branch collaborator by ID, a member who has collaborated on a branch",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "branches"
                ],
                "summary": "Get a branch collaborator by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Collaborator ID",
                        "name": "collaboratorID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.BranchCollaboratorDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/branches/reviews/{reviewID}": {
            "get": {
                "description": "Returns a review with given ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "branches"
                ],
                "summary": "Returns a review",
                "parameters": [
                    {
                        "type": "string",
                        "description": "review ID",
                        "name": "reviewID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ReviewDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        },
        "/branches/{branchID}": {
            "get": {
                "description": "Get a branch by branch ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "branches"
                ],
                "summary": "Get branch",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Branch ID",
                        "name": "branchID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.BranchDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            },
            "post": {
                "description": "Upload a new project version to a specific, preexisting, branch as a zipped quarto project",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "branches"
                ],
                "summary": "Upload a new project version to a branch",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Branch ID",
                        "name": "branchID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Repository to create",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "delete": {
                "description": "Delete a branch with given ID from database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "branches"
                ],
                "summary": "Delete a branch",
                "parameters": [
                    {
                        "type": "string",
                        "description": "branch ID",
                        "name": "branchID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/branches/{branchID}/can-review/{memberID}": {
            "get": {
                "description": "Returns true if the user fulfills the requirements to review the branch\nReturns false if user is unauthorized to review the branch",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "branches"
                ],
                "summary": "Returns whether the user is allowed to review this branch",
                "parameters": [
                    {
                        "type": "string",
                        "description": "branch ID",
                        "name": "branchID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "member ID",
                        "name": "memberID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "boolean"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/branches/{branchID}/discussions": {
            "get": {
                "description": "Returns all discussions on this version that are not a reply to another discussion\nEndpoint is offset-paginated",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "branches"
                ],
                "summary": "Returns all level 1 discussions associated with the version",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Branch ID",
                        "name": "branchID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "page query",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page size",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.DiscussionDTO"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/branches/{branchID}/file/{filepath}": {
            "get": {
                "description": "Get the contents of a single file from a project of a branch",
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "branches"
                ],
                "summary": "Get a file from a project",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Branch ID",
                        "name": "branchID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Filepath",
                        "name": "filepath",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/branches/{branchID}/render": {
            "get": {
                "description": "Get the render of the repository underlying a branch if it exists and has been rendered successfully",
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "branches"
                ],
                "summary": "Get the render of a branch",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Branch ID",
                        "name": "branchID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    },
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        },
        "/branches/{branchID}/repository": {
            "get": {
                "description": "Get the entire zipped repository of a branch",
                "produces": [
                    "application/zip"
                ],
                "tags": [
                    "branches"
                ],
                "summary": "Get the repository of a branch",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Branch ID",
                        "name": "branchID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        },
        "/branches/{branchID}/review-statuses": {
            "get": {
                "description": "Returns an array of the statuses of all the reviews of this branch",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "branches"
                ],
                "summary": "Returns status of all branch reviews",
                "parameters": [
                    {
                        "type": "string",
                        "description": "branch ID",
                        "name": "branchID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.ReviewStatus"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        },
        "/branches/{branchID}/reviews": {
            "post": {
                "description": "Adds a review to a branch",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "branches"
                ],
                "summary": "Adds a review to a branch",
                "parameters": [
                    {
                        "type": "string",
                        "description": "branch ID",
                        "name": "branchID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "review creation form",
                        "name": "form",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/forms.ReviewCreationForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/branches/{branchID}/tree": {
            "get": {
                "description": "Get the filetree of a project of a branch",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "branches"
                ],
                "summary": "Get the filetree of a project",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Branch ID",
                        "name": "branchID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "integer"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/discussions": {
            "post": {
                "description": "Create a new discussion\nEither parent ID or version ID must be specified. This determines whether it's a reply or not, respectively.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "discussions"
                ],
                "summary": "Create new discussion",
                "parameters": [
                    {
                        "description": "Discussion Creation Form",
                        "name": "form",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/forms.DiscussionCreationForm"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Parent ID",
                        "name": "parentID",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Version ID",
                        "name": "versionID",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.DiscussionDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/discussions/reports/{reportID}": {
            "get": {
                "description": "Gets a discussion report by its ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "discussions"
                ],
                "summary": "Gets a discussion report by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Report ID",
                        "name": "reportID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/reports.DiscussionReportDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/discussions/{discussionID}": {
            "get": {
                "description": "Get a discussion by discussion ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "discussions"
                ],
                "summary": "Get discussion",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Discussion ID",
                        "name": "discussionID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.DiscussionDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "delete": {
                "description": "Delete a discussion with given ID from database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "discussions"
                ],
                "summary": "Delete a discussion",
                "parameters": [
                    {
                        "type": "string",
                        "description": "discussion ID",
                        "name": "discussionID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/discussions/{discussionID}/reports": {
            "get": {
                "description": "Get all reports that have been added to this discussion",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "discussions"
                ],
                "summary": "Get all reports of this discussion",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Discussion ID",
                        "name": "discussionID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "post": {
                "description": "Create a new report for a discussion",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "discussions"
                ],
                "summary": "Add a new report to a discussion",
                "parameters": [
                    {
                        "description": "Report Creation Form",
                        "name": "form",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/forms.ReportCreationForm"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Discussion ID",
                        "name": "discussionID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ReportDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/filter/posts": {
            "get": {
                "description": "Returns all post IDs that meet the requirements in the form\nEndpoint is offset-paginated",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "filtering"
                ],
                "summary": "Filters all posts",
                "parameters": [
                    {
                        "description": "Filter form",
                        "name": "form",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/forms.FilterForm"
                        }
                    },
                    {
                        "type": "integer",
                        "description": "page query",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page size",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/filter/project-posts": {
            "get": {
                "description": "Returns all project post IDs that meet the requirements in the form\nEndpoint is offset-paginated",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "filtering"
                ],
                "summary": "Filters all project posts",
                "parameters": [
                    {
                        "description": "Filter form",
                        "name": "form",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/forms.FilterForm"
                        }
                    },
                    {
                        "type": "integer",
                        "description": "page query",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page size",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/members": {
            "get": {
                "description": "Get the ID of every member in the database.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "members"
                ],
                "summary": "Get IDs of all members",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "put": {
                "description": "Update the fields of a member",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "members"
                ],
                "summary": "Update a member",
                "parameters": [
                    {
                        "description": "Updated member",
                        "name": "member",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.MemberDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "post": {
                "description": "Create a new member from the given fields",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "members"
                ],
                "summary": "Create a new member",
                "parameters": [
                    {
                        "description": "Member Creation Form",
                        "name": "form",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/forms.MemberCreationForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.MemberDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/members/{memberID}": {
            "get": {
                "description": "Get a member by user ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "members"
                ],
                "summary": "Get member from database",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user ID",
                        "name": "memberID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.MemberDTO"
                        }
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "delete": {
                "description": "Delete a member with given ID from database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "members"
                ],
                "summary": "Delete a member",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user ID",
                        "name": "memberID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/members/{memberID}/branches": {
            "get": {
                "description": "Get all branches that this member is a collaborator of",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "members"
                ],
                "summary": "Get all branches of this member",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user ID",
                        "name": "memberID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/members/{memberID}/discussions": {
            "get": {
                "description": "Get all discussions that this member has participated in",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "members"
                ],
                "summary": "Get all discussions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user ID",
                        "name": "memberID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/members/{memberID}/posts": {
            "get": {
                "description": "Get all posts that this member is a collaborator of",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "members"
                ],
                "summary": "Get all posts of this member",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user ID",
                        "name": "memberID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/members/{memberID}/project-posts": {
            "get": {
                "description": "Get all project posts that this member is a collaborator of",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "members"
                ],
                "summary": "Get all project posts of this member",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user ID",
                        "name": "memberID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/members/{memberID}/saved-posts": {
            "get": {
                "description": "Get all posts that this member has saved",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "members"
                ],
                "summary": "Get all saved posts of this member",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user ID",
                        "name": "memberID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/members/{memberID}/saved-posts/{postID}": {
            "post": {
                "description": "Adds a post to the saved posts of a member",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "members"
                ],
                "summary": "Adds new saved post",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user ID",
                        "name": "memberID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "post ID",
                        "name": "postID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/members/{memberID}/saved-project-posts": {
            "get": {
                "description": "Get all project posts that this member has saved",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "members"
                ],
                "summary": "Get all saved project posts of this member",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user ID",
                        "name": "memberID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/members/{memberID}/saved-project-posts/{postID}": {
            "post": {
                "description": "Adds a project post to the saved project posts of a member",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "members"
                ],
                "summary": "Adds new saved project post",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user ID",
                        "name": "memberID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "post ID",
                        "name": "postID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/posts": {
            "put": {
                "description": "Update any number of the aspects of a question or discussion post",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "posts"
                ],
                "summary": "Update post",
                "parameters": [
                    {
                        "description": "Updated Post",
                        "name": "post",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.PostDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "post": {
                "description": "Create a new question or discussion post",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "posts"
                ],
                "summary": "Create new post",
                "parameters": [
                    {
                        "description": "Post Creation Form",
                        "name": "form",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/forms.PostCreationForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.PostDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/posts/collaborators/{collaboratorID}": {
            "get": {
                "description": "Get a post collaborator by ID, a member who has collaborated on a post",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "posts"
                ],
                "summary": "Get a post collaborator by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Collaborator ID",
                        "name": "collaboratorID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.PostCollaboratorDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/posts/from-github": {
            "post": {
                "description": "Create a new question or discussion post\nCreates a post in the same way as CreatePost\nHowever, the post files are imported from the given Github repository",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "posts"
                ],
                "summary": "Create new post with the version imported from github",
                "parameters": [
                    {
                        "description": "Post Creation Form",
                        "name": "form",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/forms.PostCreationForm"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Github repository url",
                        "name": "url",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.PostDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    },
                    "502": {
                        "description": "Bad Gateway"
                    }
                }
            }
        },
        "/posts/reports/{reportID}": {
            "get": {
                "description": "Gets a post report by its ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "posts"
                ],
                "summary": "Gets a post report by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Report ID",
                        "name": "reportID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/reports.PostReportDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/posts/{postID}": {
            "get": {
                "description": "Get a post by post ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "posts"
                ],
                "summary": "Get post",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Post ID",
                        "name": "postID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.PostDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "delete": {
                "description": "Delete a post with given ID from database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "posts"
                ],
                "summary": "Delete a post",
                "parameters": [
                    {
                        "type": "string",
                        "description": "post ID",
                        "name": "postID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/posts/{postID}/reports": {
            "get": {
                "description": "Get all reports that have been added to this post",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "posts"
                ],
                "summary": "Get all reports of this post",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Post ID",
                        "name": "postID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "post": {
                "description": "Create a new report for a post",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "posts"
                ],
                "summary": "Add a new report to a post",
                "parameters": [
                    {
                        "description": "Report Creation Form",
                        "name": "form",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/forms.ReportCreationForm"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Post ID",
                        "name": "postID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ReportDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/project-posts": {
            "put": {
                "description": "Update any number of the aspects of a project post",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "project-posts"
                ],
                "summary": "Update project post",
                "parameters": [
                    {
                        "description": "Updated Project Post",
                        "name": "post",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ProjectPostDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "post": {
                "description": "Create a new project post",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "project-posts"
                ],
                "summary": "Create new project post",
                "parameters": [
                    {
                        "description": "Project Post Creation Form",
                        "name": "form",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/forms.ProjectPostCreationForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ProjectPostDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/project-posts/from-github": {
            "post": {
                "description": "Create a new project post\nCreates a project post in the same way as CreateProjectPost\nHowever, the post files are imported from the given Github repository",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "project-posts"
                ],
                "summary": "Create new project post with the version imported from github",
                "parameters": [
                    {
                        "description": "Post Creation Form",
                        "name": "form",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/forms.ProjectPostCreationForm"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Github repository url",
                        "name": "url",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ProjectPostDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    },
                    "502": {
                        "description": "Bad Gateway"
                    }
                }
            }
        },
        "/project-posts/{postID}": {
            "get": {
                "description": "Get a project post by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "project-posts"
                ],
                "summary": "Get project post",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Post ID",
                        "name": "postID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ProjectPostDTO"
                        }
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "delete": {
                "description": "Delete a project post with given ID from database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "project-posts"
                ],
                "summary": "Delete a project post",
                "parameters": [
                    {
                        "type": "string",
                        "description": "post ID",
                        "name": "postID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/project-posts/{postID}/all-discussions": {
            "get": {
                "description": "Returns all discussion IDs on this project post over all its previous versions, instead of only the current version",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "project-posts"
                ],
                "summary": "Returns all discussion IDs associated with the project post",
                "parameters": [
                    {
                        "type": "string",
                        "description": "post ID",
                        "name": "postID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.DiscussionDTO"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/project-posts/{postID}/branches-by-status": {
            "get": {
                "description": "Returns all branch IDs of this project post, grouped by each branch's review status",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "project-posts"
                ],
                "summary": "Returns branch IDs grouped by each branch status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "post ID",
                        "name": "postID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/forms.GroupedBranchForm"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/tags/completion-status": {
            "get": {
                "description": "Returns every possible completion status that a Post can have",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tags"
                ],
                "summary": "Returns all completion statuses",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/tags.CompletionStatus"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/tags/feedback-preference": {
            "get": {
                "description": "Returns every possible feedback preference that a Project Post can have",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tags"
                ],
                "summary": "Returns all feedback preferences",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/tags.FeedbackPreference"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/tags/post-type": {
            "get": {
                "description": "Returns every possible post type that a Post can have",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tags"
                ],
                "summary": "Returns all post types",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/tags.PostType"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/tags/scientific": {
            "get": {
                "description": "Returns all scientific tags (an array of strings) in the database",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tags"
                ],
                "summary": "Returns all scientific tags",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/tags.ScientificFieldTag"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        }
    },
    "definitions": {
        "forms.BranchCreationForm": {
            "type": "object"
        },
        "forms.DiscussionCreationForm": {
            "type": "object",
            "properties": {
                "anonymous": {
                    "description": "If anonymous, the discussion will ignore member ID",
                    "type": "boolean"
                },
                "memberID": {
                    "type": "integer"
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "forms.FilterForm": {
            "type": "object"
        },
        "forms.GroupedBranchForm": {
            "type": "object",
            "properties": {
                "openForReviewIDs": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "peerReviewedIDs": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "rejectedIDs": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "forms.MemberCreationForm": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "fields": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/tags.ScientificFieldTag"
                    }
                },
                "firstName": {
                    "type": "string"
                },
                "institution": {
                    "type": "string"
                },
                "lastName": {
                    "type": "string"
                },
                "password": {
                    "description": "making the password just a string for now\nTODO: some hashing or semblance of security",
                    "type": "string"
                }
            }
        },
        "forms.PostCreationForm": {
            "type": "object",
            "properties": {
                "anonymous": {
                    "type": "boolean"
                },
                "authorMemberIDs": {
                    "description": "Members that are authors of the post",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "postType": {
                    "$ref": "#/definitions/tags.PostType"
                },
                "scientificFieldTags": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/tags.ScientificField"
                    }
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "forms.ProjectPostCreationForm": {
            "type": "object",
            "properties": {
                "completionStatus": {
                    "$ref": "#/definitions/tags.CompletionStatus"
                },
                "feedbackPreference": {
                    "$ref": "#/definitions/tags.FeedbackPreference"
                },
                "postCreationForm": {
                    "$ref": "#/definitions/forms.PostCreationForm"
                }
            }
        },
        "forms.ReportCreationForm": {
            "type": "object"
        },
        "forms.ReviewCreationForm": {
            "type": "object",
            "properties": {
                "branchDecision": {
                    "$ref": "#/definitions/models.BranchDecision"
                },
                "branchID": {
                    "type": "integer"
                },
                "feedback": {
                    "type": "string"
                },
                "memberID": {
                    "type": "integer"
                }
            }
        },
        "models.BranchCollaboratorDTO": {
            "type": "object",
            "properties": {
                "branchID": {
                    "type": "integer"
                },
                "collaborationType": {
                    "$ref": "#/definitions/models.CollaborationType"
                },
                "id": {
                    "type": "integer"
                },
                "memberID": {
                    "type": "integer"
                }
            }
        },
        "models.BranchDTO": {
            "type": "object",
            "properties": {
                "anonymous": {
                    "type": "boolean"
                },
                "branchTitle": {
                    "type": "string"
                },
                "collaboratorIDs": {
                    "description": "Branch metadata",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "discussionIDs": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "newPostTitle": {
                    "description": "Branch's proposed changes",
                    "type": "string"
                },
                "projectPostID": {
                    "type": "integer"
                },
                "renderStatus": {
                    "$ref": "#/definitions/models.RenderStatus"
                },
                "reviewIDs": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "reviewStatus": {
                    "$ref": "#/definitions/models.ReviewStatus"
                },
                "updatedCompletionStatus": {
                    "$ref": "#/definitions/tags.CompletionStatus"
                },
                "updatedScientificFields": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/tags.ScientificField"
                    }
                }
            }
        },
        "models.BranchDecision": {
            "type": "string",
            "enum": [
                "rejected",
                "approved"
            ],
            "x-enum-varnames": [
                "Rejected",
                "Approved"
            ]
        },
        "models.CollaborationType": {
            "type": "string",
            "enum": [
                "author",
                "contributor",
                "reviewer"
            ],
            "x-enum-varnames": [
                "Author",
                "Contributor",
                "Reviewer"
            ]
        },
        "models.DiscussionDTO": {
            "type": "object",
            "properties": {
                "anonymous": {
                    "type": "boolean"
                },
                "deleted": {
                    "type": "boolean"
                },
                "id": {
                    "type": "integer"
                },
                "memberID": {
                    "type": "integer"
                },
                "replyIDs": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "models.MemberDTO": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "institution": {
                    "type": "string"
                },
                "lastName": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "scientificFieldTags": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/tags.ScientificField"
                    }
                }
            }
        },
        "models.PostCollaboratorDTO": {
            "type": "object",
            "properties": {
                "collaborationType": {
                    "$ref": "#/definitions/models.CollaborationType"
                },
                "id": {
                    "type": "integer"
                },
                "memberID": {
                    "type": "integer"
                },
                "postID": {
                    "type": "integer"
                }
            }
        },
        "models.PostDTO": {
            "type": "object",
            "properties": {
                "collaboratorIDs": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "discussionIDs": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "postType": {
                    "$ref": "#/definitions/tags.PostType"
                },
                "scientificFieldTags": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/tags.ScientificField"
                    }
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "models.ProjectPostDTO": {
            "type": "object",
            "properties": {
                "closedBranchIDs": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "completionStatus": {
                    "$ref": "#/definitions/tags.CompletionStatus"
                },
                "feedbackPreference": {
                    "$ref": "#/definitions/tags.FeedbackPreference"
                },
                "id": {
                    "type": "integer"
                },
                "openBranchIDs": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "postDTO": {
                    "$ref": "#/definitions/models.PostDTO"
                },
                "postReviewStatusTag": {
                    "$ref": "#/definitions/tags.PostReviewStatus"
                }
            }
        },
        "models.RenderStatus": {
            "type": "string",
            "enum": [
                "success",
                "pending",
                "failure"
            ],
            "x-enum-varnames": [
                "Success",
                "Pending",
                "Failure"
            ]
        },
        "models.ReportDTO": {
            "type": "object"
        },
        "models.ReviewDTO": {
            "type": "object",
            "properties": {
                "branchDecision": {
                    "$ref": "#/definitions/models.BranchDecision"
                },
                "branchID": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "feedback": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "memberID": {
                    "type": "integer"
                }
            }
        },
        "models.ReviewStatus": {
            "type": "string",
            "enum": [
                "open for review",
                "peer reviewed",
                "rejected"
            ],
            "x-enum-varnames": [
                "BranchOpenForReview",
                "BranchPeerReviewed",
                "BranchRejected"
            ]
        },
        "reports.DiscussionReportDTO": {
            "type": "object",
            "properties": {
                "discussionID": {
                    "type": "integer"
                }
            }
        },
        "reports.PostReportDTO": {
            "type": "object",
            "properties": {
                "postID": {
                    "type": "integer"
                }
            }
        },
        "tags.CompletionStatus": {
            "type": "string",
            "enum": [
                "idea",
                "ongoing",
                "completed"
            ],
            "x-enum-varnames": [
                "Idea",
                "Ongoing",
                "Completed"
            ]
        },
        "tags.FeedbackPreference": {
            "type": "string",
            "enum": [
                "discussion",
                "formal feedback"
            ],
            "x-enum-varnames": [
                "Discussion",
                "FormalFeedback"
            ]
        },
        "tags.PostReviewStatus": {
            "type": "string",
            "enum": [
                "open",
                "revision needed",
                "reviewed"
            ],
            "x-enum-varnames": [
                "Open",
                "RevisionNeeded",
                "Reviewed"
            ]
        },
        "tags.PostType": {
            "type": "string",
            "enum": [
                "project",
                "question",
                "reflection"
            ],
            "x-enum-varnames": [
                "Project",
                "Question",
                "Reflection"
            ]
        },
        "tags.ScientificField": {
            "type": "string",
            "enum": [
                "mathematics",
                "computer science"
            ],
            "x-enum-varnames": [
                "Mathematics",
                "ComputerScience"
            ]
        },
        "tags.ScientificFieldTag": {
            "type": "object"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v2",
	Schemes:          []string{},
	Title:            "Alexandria API",
	Description:      "This is the API of Alexandria.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
